### ISSUE TITLE
Plans for lighter / LGPL version?

### ISSUE THREAD

**Issue by cdgriffith** [busimus/cutelog#10]
Hello, I really like your application and would like to include it in a project. However I only release MIT / BSD licensed code, so can only use stuff with similar or dynamically linked with LGPL licenses. 

I was curious if you perchance had a lighter version of its core functionally that you may be releasing in the future that is more friendly licensed? 

Thanks for the great program either way!

**Comment by busimus** [comment]
I received a similar request when I first released this program. At that time I dismissed it because of 2 reasons:

1. It didn't make sense to me to want a lighter license for a standalone application (as opposed to a library).
2. PyQt5 was licensed under GPLv3 so I chose it as the safest option and didn't think much of it.

The second point was dealt with now that you can choose to use PySide2 instead (which is LGPL).
But regarding the first point... If I understand licensing correctly, if you just want to use the program or redistribute it as is then there's no issue (since whatever you'd be doing wouldn't really be a derivative work). But I assume you're asking because you want to modify it or use the code in some other way? I don't have a problem with that, but I can see how the license may deter you.

I wouldn't have much of an issue re-licensing the project if it was fully mine, but it isn't -- I'd have to ask the people who have contributed to it, who may or may not agree (or even reply).

So, before bothering them, it'd be great if you could explain how GPLv3 restricts you in your case. I tried looking up some info about legal implications of using GPLv3 standalone applications in projects and couldn't find anything concrete, seemed legally wishy-washy. But it sure made me feel a glimpse of pain that this infamous license inflicts on people.

**Comment by cdgriffith** [comment]
I actually don't want to modify it, however the program the I am working on will be compiled into a binary file. From what I understand (not anything close to a lawyer) that by merely including it and using it as part of the bundle would force it into a GPL license. So I am actually right there with you on having to use PySide2 over PyQT and allowing it to be overwritten (dynamically linked).

**Comment by busimus** [comment]
I noticed the relevant project in your profile mere seconds before you responded, so now I have some context.
I _would_ like to consider such use case _not_ a derivative work since you'd be using the program for my intended purpose, but that's not how licenses work. I guess the only option is re-licensing.

Tomorrow I'll put together a pull request with the necessary changes and ask the contributors for permission before merging. Thankfully there are only two of them but one doesn't seem to be active on GitHub. So we'll see how it goes.

**Comment by cdgriffith** [comment]
That would be amazing! It might also be possible to build cutelog it into it's own executable so it's not reliant upon the compiled python version?

Just to show where I planning to use it:  https://github.com/cdgriffith/FastFlix/tree/develop#fastflix  (can test and see it's current pathetic log viewer window under the 'help' section https://ci.appveyor.com/project/cdgriffith/fastflix/builds/24308550/artifacts)

**Comment by busimus** [comment]
The license has successfully been changed to MIT.
